apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: example
    literals:
      - name=alice
      - email=alice@example.com

components:
  - ../components/common-labels
